// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxoatuhelxzfpxbquxmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4b2F0dWhlbHh6ZnB4YnF1eG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjQwNjUsImV4cCI6MjA2NDU0MDA2NX0.6DYBCIkBGJv7NqPbumC6D74z23fhVrZz7syArIS_0j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);